### ISSUE TITLE
This is my completed homework assignment

### ISSUE THREAD

**Issue by phamvuhoang** [phamvuhoang/tips#1]
So sorry about my late
/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Swift submission, phamvuhoang!

:worried: Unfortunately **there are some problems** with your submission:
* I couldn't find a walkthrough GIF referenced from your `README.md`. Please use [RecordIt](http://recordit.co) or [LICEcap](http://www.cockos.com/licecap/) to record an animated GIF of your submission going through the required stories, and include it in your `README.md`.

**Comment by phamvuhoang** [comment]
I updated the image url. Pls check

**Comment by coderschoolreview** [comment]
Did you accidentally close this issue :sweat_smile: 

:+1:  Nice job with the Tip Calculator! 

### Quick Comments:

- Basically the app can function and meeting the requirements.
- Good usage of `NSUserDefaults`. This is one of the methods to pass the data from multiple viewController. We will learn few more ways to do that. 
- Your keyboard doesn't have `.` then how do you let the user type something likes `x.yz` 
- In your setting page, you can validate the user inputs to see if 1st < 2nd < 3rd.

### Optional Suggestions to Improve

* Look into the `UIView.animateWithDuration` functions to add animations.
* You can show the keyboard immediately when app starts by using `becomeFirstResponder`
